Remove print statements with logger
maiot-io/zenml pull request #78
Opened 2021-04-24 18:16 UTC by ramitsurana

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] I have read the **CONTRIBUTING.md** document.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-04-24 18:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/maiot-io/zenml?pullRequest=78) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/maiot-io/zenml?pullRequest=78) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/maiot-io/zenml?pullRequest=78) it.</sub>

2021-04-26 09:02 UTC, hamzamaiot requested changes
Thanks @ramitsurana  ! Those prints spilled through, good to replace with proper logging. I just had one stylistic comment, so please do make that one change and ill merge right away.

Hope you are enjoying ZenML and hop on over to our Slack channel so we can say thanks directly: https://zenml.io/slack-invite !

2021-04-26 09:02 UTC, hamzamaiot commented on zenml/repo/global_config.py
> +            logger.error("Unable to load YAML file due to error: " + str(e) + ".Updating it as empty value.")
> 80 characters. We follow [PEP-8 guidelines](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) for ZenML, so please add a line break before the first place e.g.

2021-04-26 10:08 UTC, ramitsurana commented on zenml/repo/global_config.py
> +            logger.error("Unable to load YAML file due to error: " + str(e) + ".Updating it as empty value.")
Done

2021-04-26 10:13 UTC, hamzamaiot commented
@ramitsurana  It seems like the tests are failing -> It feels like there is a circular import in the new imports you introduced. Can you take a look? Otherwise I can take a look a bit later in the day

2021-04-26 11:43 UTC, htahir1 requested changes
Tests are still failing - left a comment for improving

2021-04-26 11:43 UTC, htahir1 commented on zenml/utils/requirement_utils.py
> +from zenml.logger import get_logger
I think the circular dependency lives here @ramitsurana . If you import zenml here than it wont be able to install and might result in an error like https://github.com/maiot-io/zenml/runs/2437806331?check_suite_focus=true

2021-04-26 11:43 UTC, htahir1 commented on zenml/utils/requirement_utils.py
> +from zenml.logger import get_logger
Rather do this import at the line 119

2021-04-26 11:52 UTC, ramitsurana commented
@htahir1  Cool. Thanks for letting me know. Apologies for the issue.

2021-04-26 12:01 UTC, merged

2021-04-26 12:01 UTC, htahir1 commented
All good - thanks for the PR!